export type DukampWorkspaceTab = "orders" | "receipts" | "suppliers" | "reports" | "payables";

export type DukampMenuAction = {
  key: string;
  label: string;
  tab: DukampWorkspaceTab;
  note?: string;
  screen?: string;
  prompts?: string[];
  tables?: string[];
  operational?: boolean;
  separator?: boolean;
};

export type DukampProgramMenu = {
  id: string;
  title: string;
  executable: string;
  groups: Array<{
    title: string;
    shortcuts?: string[];
    actions: DukampMenuAction[];
  }>;
};

export const PURCHASING_LAUNCHER = [
  { id: "compras", shortcut: "1", label: "Compras", executable: "cmpmenus.exe" },
  { id: "compras-2", shortcut: "2", label: "Compras 2", executable: "cmpmenu2.exe" },
  { id: "almoxarifado", shortcut: "3", label: "Almoxarifado", executable: "cmpalmox.exe" },
  { id: "nfe-loja", shortcut: "4", label: "NFE LOJA", executable: "fmpntnfe.exe EX" },
  { id: "faturamento", shortcut: "5", label: "Faturamento", executable: "fmpmnfat.exe" },
  { id: "nfe-fabrica", shortcut: "6", label: "NFE FABRICA", executable: "fmpntnfe.exe FB" },
  { id: "gerente", shortcut: "9", label: "Menu Gerente", executable: "grpmenus.exe" },
  { id: "nova-tabela", shortcut: "7", label: "NOVA TABELA", executable: "b_TABELA.bat" },
] as const;

export const WMENUS_LAUNCHERS = [
  {
    id: "w_compras",
    title: "COMPRAS",
    source: "W_COMPRAS.MNU",
    entries: [
      { label: "Compras", shortcut: "1", command: "cmpmenus.exe" },
      { label: "Compras 2", shortcut: "2", command: "cmpmenu2.exe" },
      { label: "Almoxarifado", shortcut: "3", command: "cmpalmox.exe" },
      { label: "NFE LOJA", shortcut: "4", command: "fmpntnfe.exe EX" },
      { label: "Faturamento", shortcut: "5", command: "fmpmnfat.exe" },
      { label: "NFE FABRICA", shortcut: "6", command: "fmpntnfe.exe FB" },
      { label: "Menu Gerente", shortcut: "9", command: "grpmenus.exe" },
      { label: "NOVA TABELA", shortcut: "7", command: "b_TABELA.bat" },
    ],
  },
  {
    id: "w_almoxarifado",
    title: "ALMOXARIFADO",
    source: "W_ALMOXARIFADO.mnu",
    entries: [
      { label: "Conferencia", shortcut: "1", command: "fmpconfe.exe N" },
      { label: "- Consulta Notas", shortcut: "2", command: "fmcnotas.exe" },
    ],
  },
  {
    id: "w_faturamento",
    title: "FATURAMENTO",
    source: "W_FATURAMENTO.mnu",
    entries: [
      { label: "Contas a Receber", shortcut: "1", command: "crpmenus.exe" },
      { label: "Valores Receber", shortcut: "2", command: "RRPMENUS.exe" },
      { label: "Cadastro", shortcut: "3", command: "fapmencd.exe" },
      { label: "Contas a Pagar", shortcut: "4", command: "cppmenus.exe" },
      { label: "Faturamento", shortcut: "6", command: "fmpmnfat.exe" },
      { label: "Compras", shortcut: "7", command: "cmpmenus.exe" },
      { label: "Compras_2", shortcut: "8", command: "cmpmenu2.exe" },
      { label: "Caixa", shortcut: "9", command: "b_caixa.bat" },
      { label: "Gerencidor NFE", shortcut: "5", command: "gerencianfe.exe" },
      { label: "Pedido LOJA", shortcut: "13", command: "fmppedid.exe EX" },
      { label: "NFE LOJA", shortcut: "15", command: "fmpntnfe.exe EX" },
      { label: "- Consulta Comissao", shortcut: "6", command: "fmrcomis.exe X" },
      { label: "Conferencia", shortcut: "15", command: "fmpconfe.exe N" },
      { label: "Comissao Pedido", shortcut: "4", command: "fmpmenvl.exe" },
      { label: "Emissao NFE PREVIA", shortcut: "11", command: "fmpntnfe.exe PN" },
    ],
  },
  {
    id: "w_cobranca",
    title: "COBRANCA",
    source: "W_COBRANCA.mnu",
    entries: [
      { label: "Contas a Receber", shortcut: "1", command: "crpmenus.exe" },
      { label: "Valores Receber", shortcut: "2", command: "RRPMENUS.exe" },
      { label: "Cadastro", shortcut: "3", command: "fapmencd.exe" },
      { label: "Contas a Pagar", shortcut: "4", command: "cppmenus.exe" },
      { label: "Faturamento", shortcut: "5", command: "fmpmnfat.exe" },
      { label: "Compras", shortcut: "6", command: "cmpmenus.exe" },
      { label: "Compras 2", shortcut: "7", command: "cmpmenu2.exe" },
      { label: "Cheques Pre", shortcut: "8", command: "b_cheque.bat" },
      { label: "Cartoes", shortcut: "9", command: "b_cartao.bat" },
      { label: "Caixa", shortcut: "10", command: "b_caixa.bat" },
      { label: "Controle Bancario", shortcut: "11", command: "b_bco.bat" },
      { label: "Gerencidor NFE", shortcut: "12", command: "gerencianfe.exe" },
      { label: "# Menu Financeiro", shortcut: "13", command: "financ.bat" },
      { label: "# Menu Dados Antigos", shortcut: "14", command: "dadosantigos.bat" },
      { label: "Previsoes Rec Eloy", shortcut: "15", command: "b_previs.bat" },
    ],
  },
  {
    id: "w_gerente",
    title: "GERENTE VENDAS",
    source: "W_GERENTE.MNU",
    entries: [
      { label: "NFE", shortcut: "1", command: "fmpntnfe.exe EX" },
      { label: "Cupom Fiscal", shortcut: "2", command: "fmpcupom.exe EX" },
      { label: "Cadastro Clientes", shortcut: "3", command: "fmpclien.exe" },
      { label: "Metas Venda", shortcut: "4", command: "fmrmetav.exe" },
      { label: "- Consulta Comissao", shortcut: "5", command: "fmrcomis.exe X" },
      { label: "- Consulta Notas", shortcut: "6", command: "fmcnotas.exe" },
      { label: "Compras", shortcut: "7", command: "cmpmenus.exe" },
      { label: "Compras 2", shortcut: "8", command: "cmpmenu2.exe" },
      { label: "Gerencial", shortcut: "9", command: "grpmenus.exe" },
      { label: "Receituarios", shortcut: "10", command: "repmenus.exe" },
      { label: "Declaracao Devolucao", shortcut: "11", command: "fmpdevol.exe" },
    ],
  },
  {
    id: "w_call",
    title: "CALL CENTER",
    source: "W_CALL.MNU",
    entries: [
      { label: "Televendas", shortcut: "1", command: "tepmenus.exe" },
      { label: "Emissao NFE", shortcut: "2", command: "fmpnotfa.exe X" },
      { label: "Tabela DUKAMP", shortcut: "3", command: "Xefctbweb.exe" },
      { label: "- Consulta Comissao", shortcut: "6", command: "fmrcomis.exe X" },
      { label: "- Consulta Notas", shortcut: "7", command: "fmcnotas.exe" },
      { label: "- Cons Notas ATE 2015", shortcut: "8", command: "b_notas2017.bat" },
      { label: "- Cons Titul ATE 2015", shortcut: "9", command: "b_titul2017.bat" },
      { label: "- Cons Client ATE 2015", shortcut: "10", command: "b_cli2017.bat" },
      { label: "Roteiro Entrega", shortcut: "11", command: "fmrrotei.exe" },
      { label: "Declaracao Devolucao", shortcut: "12", command: "fmpdevol.exe" },
    ],
  },
  {
    id: "w_bl_veter",
    title: "VETERINARIA",
    source: "W_BL_VETER.MNU",
    entries: [
      { label: "NFE", shortcut: "1", command: "fmpntnfe.exe VE" },
      { label: "Pedido LOJA", shortcut: "2", command: "fmppedid.exe VE" },
      { label: "Metas Venda", shortcut: "3", command: "fmrmetav.exe" },
      { label: "- Consulta Comissao", shortcut: "4", command: "fmrcomis.exe X" },
      { label: "- Consulta Notas", shortcut: "5", command: "fmcnotas.exe" },
      { label: "Televendas", shortcut: "6", command: "tepmenus.exe" },
      { label: "Tabela DUKAMP", shortcut: "7", command: "xefctbweb.exe" },
      { label: "Metas Venda Produtos", shortcut: "8", command: "fmrmetas.exe X" },
      { label: "Declaracao Devolucao", shortcut: "9", command: "fmpdevol.exe" },
      { label: "- Cons Notas ATE 2015", shortcut: "10", command: "b_notas2017.bat" },
      { label: "- Cons Titul ATE 2015", shortcut: "11", command: "b_titul2017.bat" },
      { label: "Roteiro Entrega", shortcut: "12", command: "fmrrotei.exe" },
      { label: "Clientes por Cidade", shortcut: "13", command: "facclien.exe" },
    ],
  },
  {
    id: "w_producao",
    title: "PRODUCAO",
    source: "W_PRODUCAO.mnu",
    entries: [
      { label: "Compras", shortcut: "1", command: "cmpmenus.exe" },
      { label: "Compras 2", shortcut: "2", command: "cmpmenu2.exe" },
      { label: "Autoriacao Pagamento", shortcut: "3", command: "aupmenus.exe" },
    ],
  },
  {
    id: "w_financeiro",
    title: "FINANCEIRO",
    source: "W_FINANCEIRO.mnu",
    entries: [
      { label: "- Remessa Brasil", shortcut: "1", command: "copbb.bat" },
      { label: "- Retorno Brasil", shortcut: "2", command: "retbb.bat" },
      { label: "- Remessa Bradesco(B8)", shortcut: "3", command: "rembra.bat" },
      { label: "- Retorno Bradesco(B8)", shortcut: "4", command: "retbra.bat" },
      { label: "- Remessa Safra", shortcut: "5", command: "remsafra.bat" },
      { label: "- Retorno Safra", shortcut: "6", command: "retsafra.bat" },
      { label: "- Remessa Itau", shortcut: "7", command: "remitau.bat" },
      { label: "- Retorno Itau", shortcut: "8", command: "retitau.bat" },
      { label: "- Remessa SANTANDER", shortcut: "9", command: "copban.bat" },
      { label: "- Retorno SANTANDER", shortcut: "10", command: "retbane.bat" },
      { label: "- Sicoob Remessa", shortcut: "11", command: "remsic.bat" },
      { label: "- Sicoob Retorno", shortcut: "12", command: "retsic.bat" },
    ],
  },
  {
    id: "w_dadosantigos",
    title: "DADOS ANTIGOS",
    source: "W_DADOSANTIGOS.mnu",
    entries: [
      { label: ">>> MATRIZ ATE 2015", shortcut: "1", command: "f:\\" },
      { label: "Contas a Receber", shortcut: "2", command: "dad2017\\crpmenus.exe" },
      { label: "Valores Receber", shortcut: "3", command: "dad2017\\RRPMENUS.exe" },
      { label: "Cadastro", shortcut: "4", command: "dad2017\\fapmencd.exe" },
      { label: "Faturamento", shortcut: "5", command: "dad2017\\fmpmnfat.exe" },
      { label: "Compras", shortcut: "6", command: "dad2017\\cmpmenus.exe" },
      { label: "Compras_2", shortcut: "7", command: "dad2017\\cmpmenu2.exe" },
      { label: "Contas a Pagar", shortcut: "8", command: "dad2017\\cppmenus.exe" },
      { label: "Comissao Pedido", shortcut: "9", command: "dad2017\\fmpmenvl.exe" },
    ],
  },
  {
    id: "w_web",
    title: "MENU WEB",
    source: "W_WEB.MNU",
    entries: [
      { label: "Produto WEB", shortcut: "1", command: "qgproweb.exe" },
      { label: "Gera TXT SITE", shortcut: "2", command: "cmpweb.exe" },
    ],
  },
] as const;

export const DUKAMP_PROGRAM_MENUS: Record<string, DukampProgramMenu> = {
  compras: {
    id: "compras",
    title: "MENU COMPRAS",
    executable: "cmpmenus.exe",
    groups: [
      {
        title: "MANUTENÇÃO / CADASTROS",
        shortcuts: ["1", "2", "3", "5", "6", "7", "8", "9", "0", "A"],
        actions: [
          {
            key: "price-table",
            label: "Tabela Preço / Produto",
            tab: "reports",
            screen: "[ TABELA PRECO ]",
            prompts: [
              "Produto",
              "Prz Venda",
              "% Finc. Mensal",
              "Prz Compra",
              "% Margem",
              "Ds_PRD",
              "Ds_REV",
              "Ds_Max",
              "Sld Matriz",
              "Almox",
              "Com F2 consulta Produtos ou <Esc> p/ sair",
            ],
            tables: ["dukamp_legacy_efaprodu"],
            operational: true,
          },
          {
            key: "suppliers",
            label: "Fornecedores",
            tab: "suppliers",
            screen: "[ MANUTENCAO FORNECEDORES ]",
            prompts: [
              "Codigo",
              "Razao",
              "CNPJ/CPF",
              "Inscricao",
              "Endereco",
              "Cidade",
              "Fone",
              "E-mail",
              "F2 consulta",
            ],
            tables: ["dukamp_legacy_cpaforne"],
            operational: true,
          },
          {
            key: "purchase-orders",
            label: "Pedidos de Compra",
            tab: "orders",
            screen: "[ MANUTENCAO PEDIDO COMPRA ]",
            prompts: [
              "Pedido",
              "Fornecedor",
              "Prev Faturamento",
              "Dt Pagto Antecipado",
              "Cond Pagamento",
              "Desconto",
              "Despesa Frete/Financeiro",
              "Forma Compra",
              "Ped Fornec",
              "Transportador",
              "Pendencias",
              "It Produto/Descricao Quant Prc-Unit %Dsc IPI",
              "Confirma Pedido ? <S/N>",
              "Imprime Pedido ? <S/N>",
            ],
            tables: ["dukamp_legacy_cmapedid", "dukamp_legacy_cmaitped"],
            operational: true,
          },
          {
            key: "seller-agenda",
            label: "Agenda Vendedores",
            tab: "suppliers",
            note: "cadastro auxiliar",
            screen: "CONSULTA REPRESENTANTES",
            tables: ["dukamp_legacy_faarepre"],
            operational: false,
          },
          {
            key: "purchase-index",
            label: "Índices Preço / Valores Compras",
            tab: "reports",
            operational: false,
          },
          {
            key: "product-goals",
            label: "Metas Vendas Produtos",
            tab: "reports",
            screen: "[ MANUTENCAO METAS VENDA PRODUTOS ]",
            prompts: ["Vendedor", "Data Validade Inicial", "Produto", "Meta"],
            operational: false,
          },
          {
            key: "units",
            label: "Unidades de Medida",
            tab: "reports",
            screen: "[ MANUTENCAO UNIDADES PRODUTOS ]",
            operational: false,
          },
          {
            key: "payment-goals",
            label: "Metas Pagamentos Compras",
            tab: "payables",
            operational: false,
          },
          {
            key: "product-areas",
            label: "Áreas Produtos / Responsável",
            tab: "reports",
            screen: "[ MANUTENCAO AREA PRODUTOS ]",
            operational: false,
          },
          {
            key: "delivery-route",
            label: "Roteiro de Entrega",
            tab: "receipts",
            screen: "[ MANUTENCAO ROTEIRO ENTREGA ]",
            prompts: ["Codigo Cliente", "F2 Consulta"],
            operational: false,
          },
        ],
      },
      {
        title: "RELATÓRIOS",
        shortcuts: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0"],
        actions: [
          {
            key: "price-report",
            label: "Tabela de Preço",
            tab: "reports",
            screen: "[ EMISSAO TABELA PRECO ]",
            prompts: ["Nro Coluna Tabela", "Ordem emissao", "Video ou Impressora"],
            operational: true,
          },
          {
            key: "purchase-suggestion",
            label: "Produtos / Sugestão Compras",
            tab: "reports",
            screen: "[ RELATORIO PRODUTOS/SUGESTAO COMPRAS ]",
            prompts: ["ABC Produtos", "Com/Sem Giro", "Com Complemento", "Pedidos com PENDENCIA"],
            operational: true,
          },
          {
            key: "sales-award-products",
            label: "Vendas / Premiação Cliente / Produto",
            tab: "reports",
            screen: "[ RELATORIO PREMIACAO VENDA ]",
            operational: false,
          },
          {
            key: "abc-supplier",
            label: "Curva ABC Fornecedor / Produto / Grupo",
            tab: "reports",
            operational: false,
          },
          {
            key: "cost-sale",
            label: "Produtos Custo / Venda",
            tab: "reports",
            screen: ">>> CUSTO PRODUTO <<<",
            prompts: ["Fornecedor Dt_Compr Quant Prc_Rec %Ipi %Icm CTB Vl_ST %ST Vl_Custo"],
            operational: true,
          },
          {
            key: "abc-seller",
            label: "Curva ABC Vendedor / Clientes",
            tab: "reports",
            operational: false,
          },
          {
            key: "sales-award-orders",
            label: "Vendas / Premiação Pedidos",
            tab: "reports",
            operational: false,
          },
          {
            key: "pis-cofins",
            label: "Compras Produtos PIS / COFINS",
            tab: "receipts",
            screen: "[ RELATORIO PROD COMPRAS SEM PIS/COFINS ]",
            operational: false,
          },
          { key: "promotions", label: "Produtos em Promoção", tab: "reports", operational: true },
          { key: "abc-purchases", label: "Curva ABC Compras", tab: "reports", operational: false },
        ],
      },
      {
        title: "CONSULTAS",
        shortcuts: ["1", "3", "4", "5", "6", "7", "8", "9", "0", "A"],
        actions: [
          {
            key: "sales-margin",
            label: "Margem Venda",
            tab: "reports",
            screen: "CONSULTA MARGEM",
            operational: true,
          },
          {
            key: "sales-invoices",
            label: "Notas Fiscal Venda",
            tab: "receipts",
            note: "arquivo fiscal",
            screen: "[ CONSULTA NOTAS FISCAIS ]",
            tables: ["dukamp_legacy_faanotas"],
            operational: false,
          },
          {
            key: "customer-titles",
            label: "Clientes / Títulos",
            tab: "payables",
            note: "financeiro",
            tables: ["dukamp_legacy_cratitul"],
            operational: false,
          },
          {
            key: "supplier-titles",
            label: "Fornecedor / Títulos",
            tab: "payables",
            screen: "CONSULTA TITULOS",
            tables: ["dukamp_legacy_cpatitup"],
            operational: true,
          },
          {
            key: "sales-orders",
            label: "Pedidos Venda",
            tab: "orders",
            note: "faturamento",
            tables: ["dukamp_legacy_faapedid"],
            operational: false,
          },
          { key: "sales-commission", label: "Comissão Venda", tab: "reports", operational: false },
          { key: "commission-test", label: "Comissão (Teste)", tab: "reports", operational: false },
          {
            key: "product-award",
            label: "Prêmio Metas Venda Produto",
            tab: "reports",
            operational: false,
          },
          {
            key: "seller-goal",
            label: "Meta Venda por Vendedor",
            tab: "reports",
            operational: false,
          },
          {
            key: "product-log",
            label: "Log Produtos",
            tab: "reports",
            screen: "CONSULTA LOG",
            tables: ["dukamp_legacy_efalogpr"],
            operational: false,
          },
        ],
      },
      {
        title: "OPERAÇÕES ESPECIAIS",
        shortcuts: ["1", "2", "3", "4"],
        actions: [
          {
            key: "special-empty",
            label: "(rotina especial sob senha)",
            tab: "reports",
            note: "requer liberação",
            operational: false,
          },
        ],
      },
    ],
  },
  "compras-2": {
    id: "compras-2",
    title: "MENU COMPRAS 2",
    executable: "cmpmenu2.exe",
    groups: [
      {
        title: "MANUTENÇÃO / CADASTROS",
        shortcuts: ["1", "2", "3", "4", "5", "6", "8", "9", "0", "B"],
        actions: [
          {
            key: "purchase-orders",
            label: "Pedidos de Compra",
            tab: "orders",
            screen: "[ MANUTENCAO PEDIDO COMPRA ]",
            prompts: [
              "Pedido",
              "Fornecedor",
              "Prev Faturamento",
              "Forma Compra",
              "Confirma Pedido ? <S/N>",
            ],
            tables: ["dukamp_legacy_cmapedid", "dukamp_legacy_cmaitped"],
            operational: true,
          },
          {
            key: "product-movement",
            label: "Movimentações Produtos",
            tab: "receipts",
            screen: "[ MOVIMENTACAO PRODUTOS LOJA ]",
            prompts: [
              "Data Movimento",
              "Produto : Classificacao",
              "Custo Compra",
              "Data Compra",
              "Custo Medio",
              "Fornecedor",
              "Saldo",
              "Quantidade",
            ],
            operational: true,
          },
          {
            key: "purchase-entry",
            label: "Entrada Notas Compra",
            tab: "receipts",
            screen: "[ ENTRADA COMPRAS ]",
            prompts: [
              "Nr Nota Fiscal",
              "Fornec. Fiscal",
              "Estado",
              "Vlr Total Nota",
              "Frete Sem Icms",
              "Cond Pagamento",
              "Com <F2> Cons Forn, <F4> Cons Ult Notas, <F8> Importa XML ou <Esc> sai",
              "Atualiza Cst/Est",
            ],
            tables: ["dukamp_legacy_cmanoten", "dukamp_legacy_cmaitent"],
            operational: true,
          },
          {
            key: "release-entry",
            label: "Liberar Produto Notas Compra",
            tab: "receipts",
            screen: "NFE NAO LIBERADA",
            prompts: [
              "Pedido Item Quantidade Prv_Entr Fornecedor Ped_Fornecedor",
              "CONSULTA ENTRADAS NAO LIBERADAS",
            ],
            operational: true,
          },
          {
            key: "suppliers",
            label: "Fornecedores",
            tab: "suppliers",
            screen: "[ MANUTENCAO FORNECEDORES ]",
            tables: ["dukamp_legacy_cpaforne"],
            operational: true,
          },
          {
            key: "product-groups",
            label: "Grupo Produtos",
            tab: "reports",
            screen: "[ MANUTENCAO GRUPO PRODUTOS ]",
            operational: false,
          },
          {
            key: "seller-goals",
            label: "Metas Vendas Vendedor Mensal",
            tab: "reports",
            screen: "[ MANUTENCAO METAS VENDA MENSAL ]",
            operational: false,
          },
          {
            key: "seller-block",
            label: "Bloqueio Vendedor para Venda",
            tab: "reports",
            screen: "BLOQUEIO VENDEDOR",
            operational: false,
          },
          {
            key: "price-table",
            label: "Tabela Preço / Produto",
            tab: "reports",
            screen: "[ TABELA PRECO ]",
            operational: true,
          },
          {
            key: "validity",
            label: "Validades Produtos",
            tab: "reports",
            screen: "[ MANUTENCAO VALIDADE PRODUTOS ]",
            prompts: [
              "Produto",
              "Validade",
              "Com Esc aceita opcao ou F2 Cons Produto F3 Cons Validades",
            ],
            tables: ["dukamp_legacy_efavalid"],
            operational: false,
          },
        ],
      },
      {
        title: "RELATÓRIOS",
        shortcuts: ["1", "2", "3", "4", "6", "7", "8", "9", "0", "A", "C", "D", "E", "F", "G"],
        actions: [
          { key: "open-orders", label: "Pedidos Compra em Aberto", tab: "orders" },
          { key: "open-orders-summary", label: "Resumo Pedidos em Aberto", tab: "orders" },
          { key: "purchase-icms", label: "Notas Compra / ICMS", tab: "receipts" },
          { key: "matrix-stock", label: "Matriz Levantamento Saldo", tab: "reports" },
          { key: "negative-stock", label: "Produtos Saldo Negativo", tab: "reports" },
          { key: "product-check", label: "Conferência Produtos", tab: "reports" },
          { key: "product-groups-report", label: "Grupo Produtos", tab: "reports" },
          { key: "unreleased-notes", label: "Notas Compra Não Liberadas", tab: "receipts" },
          { key: "segment-purchases", label: "Compras por Segmento", tab: "reports" },
          { key: "stock-difference", label: "Faltam / Excesso Saldo Produtos", tab: "reports" },
          { key: "freight-documents", label: "Conhecimentos Fretes", tab: "receipts" },
          { key: "validity-report", label: "Validade Produtos", tab: "reports" },
          { key: "purchase-cfop", label: "Notas Compra / ICMS por CFOP", tab: "receipts" },
          { key: "purchase-goals", label: "Metas Compras", tab: "reports" },
          { key: "changed-prices", label: "Produtos Alterados Preço", tab: "reports" },
        ],
      },
      {
        title: "CONSULTAS",
        shortcuts: ["1", "2", "3", "4", "5", "6"],
        actions: [
          {
            key: "sales-invoices",
            label: "Notas Fiscal Venda",
            tab: "receipts",
            screen: "[ CONSULTA NOTAS FISCAIS ]",
            operational: false,
          },
          {
            key: "customer-titles",
            label: "Clientes / Títulos",
            tab: "payables",
            operational: false,
          },
          { key: "product-log", label: "Log Produtos", tab: "reports", operational: false },
          {
            key: "supplier-titles",
            label: "Fornecedor / Títulos",
            tab: "payables",
            screen: "CONSULTA TITULOS",
            operational: true,
          },
          {
            key: "change-product-group",
            label: "Altera Grupo Produtos",
            tab: "reports",
            operational: false,
          },
          {
            key: "cancel-orders",
            label: "Cancelamento Pedidos",
            tab: "orders",
            screen: "CANCELAMENTO PEDIDOS",
            operational: true,
          },
        ],
      },
      {
        title: "OPERAÇÕES ESPECIAIS",
        shortcuts: ["1", "2", "3", "4"],
        actions: [
          {
            key: "special-empty",
            label: "(rotina especial sob senha)",
            tab: "reports",
            operational: false,
          },
        ],
      },
    ],
  },
  almoxarifado: {
    id: "almoxarifado",
    title: "MENU ALMOXARIFADO",
    executable: "cmpalmox.exe",
    groups: [
      {
        title: "MANUTENÇÃO / CADASTROS",
        shortcuts: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "A"],
        actions: [
          {
            key: "warehouse-movement",
            label: "Movimentações Produtos Almx",
            tab: "receipts",
            screen: "[ MOVIMENTACAO PRODUTOS ALMOXARIFADO ]",
            prompts: ["Data Movimento", "Produto : Classif", "Fornecedor", "Saldo", "Quantidade"],
            tables: ["dukamp_legacy_efaprodu", "dukamp_legacy_faaentit"],
            operational: false,
          },
          {
            key: "stock-inconsistency",
            label: "Movimentações Inconsist Sld",
            tab: "reports",
            screen: "[ MOV ALMOXARIFADO INCONSISTENCIA ]",
            prompts: ["Produto", "Saldo_Est", "Saldo_Alm"],
            tables: ["dukamp_legacy_faaentsq"],
            operational: false,
          },
          {
            key: "separator-1",
            label: "---------------------------",
            tab: "receipts",
            separator: true,
          },
          {
            key: "freight-payable",
            label: "Controle Frete Pagar",
            tab: "payables",
            screen: "[ CONTROLE FRETE A PAGAR ]",
            prompts: [
              "Nr Nota",
              "Dat Emiss Nota",
              "Valor Nota",
              "Frete Nota",
              "Cliente",
              "Vl Frete Pagar",
              "Dt Emis Boleto",
            ],
            tables: ["dukamp_legacy_faafrete"],
            operational: false,
          },
          {
            key: "purchase-orders",
            label: "Pedidos Compra",
            tab: "orders",
            screen: "[ MANUTENCAO PEDIDO COMPRA ]",
            prompts: [
              "Pedido",
              "Fornecedor",
              "Prev Faturamento",
              "Dt Pagto Antecipado",
              "Forma Compra",
              "Ped Fornec",
            ],
            tables: ["dukamp_legacy_cmapedid", "dukamp_legacy_cmaitped"],
            operational: true,
          },
          {
            key: "barcode",
            label: "Codigo de Barras",
            tab: "reports",
            screen: "[ MANUTENCAO CODIGO BARRAS ]",
            prompts: ["Produto", "Codigo Barra", "F2 Consulta"],
            tables: ["dukamp_legacy_faabarra"],
            operational: false,
          },
          {
            key: "validity",
            label: "Validades Produtos",
            tab: "reports",
            screen: "[ MANUTENCAO VALIDADE PRODUTOS ]",
            prompts: ["Produto", "Validade", "F2 Cons Produto F3 Cons Validades"],
            tables: ["dukamp_legacy_efavalid"],
            operational: false,
          },
          {
            key: "product-location",
            label: "Alteracao Produto(Local)",
            tab: "reports",
            screen: "[ MANUTENCAO PRODUTOS ]",
            prompts: ["Produto : Classificacao", "Local", "Local_Almox"],
            tables: ["dukamp_legacy_efaprodu"],
            operational: true,
          },
          {
            key: "purchase-entry",
            label: "Entrada Notas Compra",
            tab: "receipts",
            screen: "[ ENTRADA COMPRAS ]",
            prompts: [
              "Nr Nota Fiscal",
              "Fornec. Fiscal",
              "Estado",
              "Vlr Total Nota",
              "Frete Sem Icms",
              "Atualiza Cst/Est",
              "Vlr Icms",
              "Vlr Base Icms",
            ],
            tables: ["dukamp_legacy_cmanoten", "dukamp_legacy_cmaitent"],
            operational: true,
          },
          {
            key: "suppliers",
            label: "Manutencao Fornecedores",
            tab: "suppliers",
            screen: "[ MANUTENCAO FORNECEDORES ]",
            prompts: ["Codigo", "Razao", "CNPJ/CPF", "F2 consulta"],
            tables: ["dukamp_legacy_cpaforne"],
            operational: true,
          },
          {
            key: "factory-movement",
            label: "Movimentacoes Produtos Fabr",
            tab: "receipts",
            screen: "[ MOVIMENT PRODUTOS FABRICA ]",
            prompts: ["Data", "Produto", "Saldo Fabr", "Quantidade"],
            tables: ["dukamp_legacy_efaprodu"],
            operational: false,
          },
        ],
      },
      {
        title: "RELATÓRIOS",
        shortcuts: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D"],
        actions: [
          {
            key: "warehouse-balance",
            label: "Matriz Levant Saldo Almox",
            tab: "reports",
            screen: "- RELATORIO DE SALDOS ORDEM ALFABETICA",
            prompts: ["Local Almox", "Com 0000 emite para todos", "Video ou Impressora"],
            tables: ["dukamp_legacy_efaprodu"],
            operational: true,
          },
          {
            key: "count-difference",
            label: "Saldo Inconsistencia Contag",
            tab: "reports",
            operational: false,
          },
          {
            key: "movement-check",
            label: "Conferencia Prod Mov Almox",
            tab: "reports",
            screen: "[ REL CONFERENCIA PRODUTOS ALMOXARIFADO ]",
            prompts: ["Area Almoxarifado", "Emissao com Saldo Estoque"],
            operational: false,
          },
          {
            key: "separator-rel",
            label: "---------------------------",
            tab: "reports",
            separator: true,
          },
          {
            key: "open-orders",
            label: "Pedidos Compra em Aberto",
            tab: "orders",
            screen: "[ RELATORIO PEDIDOS COMPRA ]",
            operational: true,
          },
          {
            key: "matrix-balance",
            label: "Matriz Levantamento Saldo",
            tab: "reports",
            operational: true,
          },
          {
            key: "negative-stock",
            label: "Prod Saldo Negativo",
            tab: "reports",
            screen: "- RELATORIO PRODUTOS COM SALDO NEGATIVO",
            operational: true,
          },
          {
            key: "replacement",
            label: "Conferencia/Reposicao/Geral",
            tab: "reports",
            operational: false,
          },
          {
            key: "unreleased-notes",
            label: "Notas Compra Nao Liberadas",
            tab: "receipts",
            screen: "- RELATORIO NOTAS ENTRADA COMPRA NAO LIBERADA P/ ESTOQUE",
            operational: true,
          },
          {
            key: "barcode-label",
            label: "Etiqueta Barra Impr",
            tab: "reports",
            operational: false,
          },
          {
            key: "validity-report",
            label: "Validade Produtos",
            tab: "reports",
            operational: false,
          },
          {
            key: "package-check",
            label: "Notas/Itens NAO CONF PACOTE",
            tab: "receipts",
            operational: false,
          },
          {
            key: "pending-orders",
            label: "Pedidos Pendencia em Aberto",
            tab: "orders",
            operational: true,
          },
        ],
      },
      {
        title: "CONSULTAS",
        shortcuts: ["1", "2", "3", "4"],
        actions: [
          {
            key: "sales-invoices",
            label: "Notas Fiscal Venda",
            tab: "receipts",
            screen: "[ CONSULTA NOTAS FISCAIS ]",
            tables: ["dukamp_legacy_faanotas"],
            operational: false,
          },
          {
            key: "product-log",
            label: "Log Produtos",
            tab: "reports",
            screen: "CONSULTA LOG",
            tables: ["dukamp_legacy_efalogpr"],
            operational: false,
          },
          {
            key: "products-table",
            label: "Produtos/Tabela",
            tab: "reports",
            screen: "[ TABELA PRECO ]",
            operational: true,
          },
          {
            key: "supplier-titles",
            label: "Fornecedor/Titulos",
            tab: "payables",
            screen: "CONSULTA TITULOS",
            tables: ["dukamp_legacy_cpatitup"],
            operational: true,
          },
        ],
      },
      {
        title: "OPERAÇÕES ESPECIAIS",
        shortcuts: ["1", "2", "3", "4"],
        actions: [
          {
            key: "special-empty",
            label: "(reservado - sem rotina ativa)",
            tab: "reports",
            note: "ESPECIAIS vazio no executável",
            operational: false,
          },
        ],
      },
    ],
  },
};

const simpleProgram = (
  id: string,
  title: string,
  executable: string,
  actions: DukampMenuAction[],
): DukampProgramMenu => ({ id, title, executable, groups: [{ title: "OPERAÇÕES", actions }] });

DUKAMP_PROGRAM_MENUS["nfe-loja"] = simpleProgram("nfe-loja", "NFE LOJA", "fmpntnfe.exe EX", [
  { key: "issue-nfe", label: "Emissão de NFe Loja", tab: "receipts" },
  { key: "sales-invoices", label: "Consulta Notas Fiscais", tab: "receipts" },
  { key: "xml-danfe", label: "XML / DANFE", tab: "receipts" },
]);
DUKAMP_PROGRAM_MENUS["nfe-fabrica"] = simpleProgram(
  "nfe-fabrica",
  "NFE FÁBRICA",
  "fmpntnfe.exe FB",
  [
    { key: "issue-nfe", label: "Emissão de NFe Fábrica", tab: "receipts" },
    { key: "factory-stock", label: "Movimentação Estoque Fábrica", tab: "receipts" },
    { key: "xml-danfe", label: "XML / DANFE", tab: "receipts" },
  ],
);
DUKAMP_PROGRAM_MENUS.faturamento = simpleProgram(
  "faturamento",
  "MENU FATURAMENTO",
  "fmpmnfat.exe",
  [],
);
DUKAMP_PROGRAM_MENUS.faturamento.groups = [
  {
    title: "MANUTENÇÕES",
    shortcuts: ["1", "2", "3", "5", "6", "7"],
    actions: [
      { key: "commission-values", label: "Valores Comissões", tab: "reports" },
      { key: "commission-discounts", label: "Descontos Comissões", tab: "reports" },
      { key: "customers", label: "Clientes", tab: "suppliers" },
      { key: "freight-percentages", label: "Percentuais de Frete", tab: "reports" },
      { key: "customer-rates", label: "Tabela / Taxas Cliente", tab: "reports" },
      { key: "delivery-route", label: "Roteiro de Entrega", tab: "receipts" },
    ],
  },
  {
    title: "RELATÓRIOS",
    shortcuts: ["2", "3", "4", "5", "6", "9", "0", "A", "B", "C", "D", "E", "F", "G", "H"],
    actions: [
      { key: "sales-commission", label: "Vendas / Comissões", tab: "reports" },
      { key: "invoice-release-password", label: "Senha Liberação Notas", tab: "reports" },
      { key: "open-sales-orders", label: "Pedidos em Aberto", tab: "orders" },
      { key: "sales-segment", label: "Vendas por Segmento", tab: "reports" },
      { key: "commission-segment", label: "Comissões por Segmento", tab: "reports" },
      { key: "cancelled-documents", label: "Notas / Pedidos Cancelados", tab: "receipts" },
      { key: "invoice-operations", label: "Operações / Notas", tab: "receipts" },
      { key: "tax-substitution-sales", label: "Vendas Substituição Tributária", tab: "reports" },
      { key: "pis-cofins-sales", label: "Venda Produtos PIS / COFINS", tab: "reports" },
      { key: "issued-invoices", label: "Notas Emitidas", tab: "receipts" },
      { key: "customer-credit-limit", label: "Clientes Limite Crédito", tab: "reports" },
      { key: "invoice-freight", label: "Fretes Notas Fiscais", tab: "payables" },
      { key: "invoice-bank-slips", label: "Emissão Boletos NF Laser", tab: "payables" },
      { key: "icms-sector", label: "ICMS por Setor", tab: "reports" },
      { key: "delivery-route-report", label: "Roteiro de Entrega", tab: "receipts" },
    ],
  },
  {
    title: "CONSULTAS",
    shortcuts: ["1", "2", "3", "4", "5"],
    actions: [
      { key: "sales-invoice-query", label: "Nota Fiscal", tab: "receipts" },
      { key: "customer-titles", label: "Clientes / Títulos", tab: "payables" },
      { key: "product-log", label: "Log Produtos", tab: "reports" },
      { key: "bank-slip-log", label: "Log Boletos", tab: "payables" },
      { key: "sales-orders", label: "Pedidos Venda", tab: "orders" },
    ],
  },
];
DUKAMP_PROGRAM_MENUS.gerente = {
  id: "gerente",
  title: "MENU COORDENAÇÃO DE VENDAS",
  executable: "grpmenus.exe",
  groups: [
    {
      title: "MANUTENÇÕES",
      shortcuts: ["1", "3", "4", "5", "6"],
      actions: [
        { key: "price-table", label: "Tabela Preço / Produto", tab: "reports" },
        { key: "sales-goals", label: "Metas Vendas Produtos", tab: "reports" },
        { key: "monthly-goals", label: "Metas Vendas Vendedor Mensal", tab: "reports" },
        { key: "seller-block", label: "Bloqueio Vendedor Emissão Nota", tab: "reports" },
        { key: "customer-rates", label: "Tabela / Taxas / E-mail Cliente", tab: "reports" },
      ],
    },
    {
      title: "RELATÓRIOS",
      shortcuts: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "A", "B", "C"],
      actions: [
        { key: "open-orders", label: "Pedidos Compra em Aberto", tab: "orders" },
        { key: "matrix-stock", label: "Matriz Levantamento Saldo", tab: "reports" },
        { key: "negative-stock", label: "Produtos Saldo Negativo", tab: "reports" },
        { key: "product-check", label: "Conferência Produtos", tab: "reports" },
        { key: "product-groups", label: "Grupo Produtos", tab: "reports" },
        { key: "unreleased-notes", label: "Notas Compra Não Liberadas", tab: "receipts" },
        {
          key: "sales-award-products",
          label: "Vendas / Premiação Cliente / Produto",
          tab: "reports",
        },
        { key: "abc-supplier", label: "Curva ABC Fornecedor / Produto / Grupo", tab: "reports" },
        { key: "abc-seller", label: "Curva ABC Vendedor / Clientes", tab: "reports" },
        { key: "sales-award-orders", label: "Vendas / Premiação Pedidos", tab: "reports" },
        { key: "stock-difference", label: "Faltam / Excesso Saldo Produtos", tab: "reports" },
        { key: "promotions", label: "Produtos em Promoção", tab: "reports" },
        { key: "validity-report", label: "Validade Produtos", tab: "reports" },
      ],
    },
    {
      title: "CONSULTAS",
      shortcuts: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
      actions: [
        { key: "sales-margin", label: "Margem Venda", tab: "reports" },
        { key: "sales-invoices", label: "Notas Fiscal Venda", tab: "receipts" },
        { key: "customer-titles", label: "Clientes / Títulos", tab: "payables" },
        { key: "product-log", label: "Log Produtos", tab: "reports" },
        { key: "sales-orders", label: "Pedidos Venda", tab: "orders" },
        { key: "sales-commission", label: "Comissão Venda", tab: "reports" },
        { key: "commission-test", label: "Comissão (Teste)", tab: "reports" },
        { key: "product-award", label: "Prêmio Metas Venda Produto", tab: "reports" },
        { key: "seller-goal", label: "Meta Venda por Vendedor", tab: "reports" },
      ],
    },
  ],
};
DUKAMP_PROGRAM_MENUS["nova-tabela"] = simpleProgram("nova-tabela", "NOVA TABELA", "b_TABELA.bat", [
  {
    key: "price-table",
    label: "Tabela Preço / Produto",
    tab: "reports",
    screen: "[ TABELA PRECO ]",
    operational: true,
  },
  {
    key: "cost-sale",
    label: "Custo / Venda / Margem",
    tab: "reports",
    screen: ">>> CUSTO PRODUTO <<<",
    operational: true,
  },
  {
    key: "changed-prices",
    label: "Histórico Alteração de Preços",
    tab: "reports",
    screen: "LOG CORRECAO PRECO",
    tables: ["dukamp_legacy_efalogpr"],
    operational: false,
  },
]);

function legacyProgram(
  id: string,
  title: string,
  executable: string,
  maintenance: Array<[string, string, string[]]>,
  reports: Array<[string, string, string[]]>,
  consultations: Array<[string, string, string[]]>,
): void {
  const toAction = ([shortcut, label, tables]: [string, string, string[]]): DukampMenuAction => ({
    key: `${id}-${shortcut.toLowerCase()}`,
    label,
    tab: tables.some((t) => t.includes("cpa") || t.includes("cra") || t.includes("rra"))
      ? "payables"
      : tables.some((t) => t.includes("faaclien") || t.includes("cpaforne"))
        ? "suppliers"
        : tables.some((t) => t.includes("cma") || t.includes("faanota"))
          ? "receipts"
          : "reports",
    screen: `[ ${label.toUpperCase()} ]`,
    tables,
    operational: false,
  });
  DUKAMP_PROGRAM_MENUS[id] = {
    id,
    title,
    executable,
    groups: [
      {
        title: "MANUTENÇÕES",
        shortcuts: maintenance.map(([s]) => s),
        actions: maintenance.map((m) => toAction(m)),
      },
      {
        title: "RELATÓRIOS",
        shortcuts: reports.map(([s]) => s),
        actions: reports.map((m) => toAction(m)),
      },
      {
        title: "CONSULTAS",
        shortcuts: consultations.map(([s]) => s),
        actions: consultations.map((m) => toAction(m)),
      },
      {
        title: "OPERAÇÕES ESPECIAIS",
        shortcuts: ["1", "2", "3", "4"],
        actions: [
          {
            key: `${id}-special`,
            label: "(rotina especial sob senha)",
            tab: "reports",
            operational: false,
          },
        ],
      },
    ],
  };
}

legacyProgram(
  "contas-pagar",
  "MENU CONTAS A PAGAR",
  "cppmenus.exe",
  [
    ["3", "Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["D", "Metas Grupo Despesas", ["dukamp_legacy_cpametas"]],
    ["E", "Agenda/Contas", ["dukamp_legacy_cpagenda"]],
    ["F", "Adiantamentos Fornecedor", ["dukamp_legacy_cpaadfor"]],
  ],
  [
    ["2", "Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["3", "Titulos", ["dukamp_legacy_cpatitup"]],
    ["8", "Titulos Aberto por Vencimento", ["dukamp_legacy_cpatitup"]],
    ["0", "Titulos Por Grupo Despesas", ["dukamp_legacy_cpatitup"]],
    ["C", "Etiqueta de Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["D", "Ficha de Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["E", "Resumo Metas/Despesas", ["dukamp_legacy_cpametas"]],
    ["F", "ABC Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["G", "Adiantamentos Fornecedores", ["dukamp_legacy_cpaadfor"]],
  ],
  [["1", "Fornecedores/Titulos", ["dukamp_legacy_cpaforne", "dukamp_legacy_cpatitup"]]],
);

legacyProgram(
  "contas-receber",
  "MENU CONTAS RECEBER",
  "crpmenus.exe",
  [
    ["9", "Bxa/Retor Titulos", ["dukamp_legacy_cratitul"]],
    ["0", "Despesas Titulos", ["dukamp_legacy_cratitul"]],
    ["B", "Adian/Cred Client", ["dukamp_legacy_cratitul"]],
  ],
  [
    ["2", "Titulos", ["dukamp_legacy_cratitul"]],
    ["4", "Saldo Carteiras", ["dukamp_legacy_cracabcp"]],
    ["7", "Historico Cliente", ["dukamp_legacy_rratitul"]],
    ["8", "Titulos Bco/Agencia Cob", ["dukamp_legacy_cratitul"]],
    ["A", "Titulos por Cidade", ["dukamp_legacy_cratitul"]],
    ["B", "Boleto Cobranca", ["dukamp_legacy_cratitul"]],
    ["D", "Ficha de Clientes", ["dukamp_legacy_faaclien"]],
    ["F", "Adiant/Credito Clientes", ["dukamp_legacy_cratitul"]],
  ],
  [
    ["1", "Clientes/Titulos", ["dukamp_legacy_faaclien", "dukamp_legacy_cratitul"]],
    ["2", "Titulo/Numero", ["dukamp_legacy_cratitul"]],
    ["3", "Log/Instr Titulos", ["dukamp_legacy_cralogti"]],
  ],
);

legacyProgram(
  "valores-receber",
  "MENU VALORES RECEBER",
  "rrpmenus.exe",
  [
    ["9", "Bxa/Retor Titulos", ["dukamp_legacy_rratitul"]],
    ["0", "Despesas Titulos", ["dukamp_legacy_rratitul"]],
  ],
  [
    ["2", "Titulos", ["dukamp_legacy_rratitul"]],
    ["4", "Saldo Carteiras", ["dukamp_legacy_cracabcp"]],
    ["7", "Historico Cliente", ["dukamp_legacy_rratitul"]],
    ["8", "Titulos Cart/Agencia Cob", ["dukamp_legacy_rratitul"]],
    ["A", "Titulos por Cidade", ["dukamp_legacy_rratitul"]],
    ["B", "Boleto Cobranca", ["dukamp_legacy_rratitul"]],
  ],
  [
    ["1", "Clientes/Titulos", ["dukamp_legacy_faaclien", "dukamp_legacy_rratitul"]],
    ["2", "Titulo/Numero", ["dukamp_legacy_rratitul"]],
    ["3", "Log Titulos", ["dukamp_legacy_cralogti"]],
  ],
);

legacyProgram(
  "televendas",
  "MENU TELEVENDAS",
  "tepmenus.exe",
  [
    ["1", "Historico Cliente", ["dukamp_legacy_faaclien"]],
    ["2", "Cliente por Cidade", ["dukamp_legacy_faacidad"]],
  ],
  [["2", "Contatos de Clientes", ["dukamp_legacy_faaclien"]]],
  [
    ["1", "Nota Fiscal", ["dukamp_legacy_faanotas"]],
    ["2", "Clientes/Titulos", ["dukamp_legacy_faaclien", "dukamp_legacy_cratitul"]],
    ["3", "Log Produtos", ["dukamp_legacy_efalogpr"]],
    ["4", "Pedidos", ["dukamp_legacy_faapedid"]],
  ],
);

legacyProgram(
  "receitas",
  "MENU RECEITAS",
  "repmenus.exe",
  [
    ["1", "Produtos com Receitas", ["dukamp_legacy_efaprodu"]],
    ["2", "Cultura", ["dukamp_legacy_efaprodu"]],
    ["3", "Recomendacoes Tecnicas", ["dukamp_legacy_efaprodu"]],
    ["4", "ARTs", ["dukamp_legacy_efaprodu"]],
    ["5", "Profissional Responsavel", ["dukamp_legacy_faarepre"]],
  ],
  [
    ["1", "Produtos com Receita", ["dukamp_legacy_efaprodu"]],
    ["2", "Reemissao Receitas", ["dukamp_legacy_efaprodu"]],
    ["3", "Venda Produtos Arts_Sequenc", ["dukamp_legacy_faanotai"]],
  ],
  [],
);

legacyProgram(
  "autorizacao-pagamento",
  "AUTORIZACAO PAGAMENTO",
  "aupmenus.exe",
  [
    ["1", "Manutencao Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["2", "Manutencao Autorizacao Pagto", ["dukamp_legacy_cpaautpg"]],
    ["3", "Emissao Autorizacao Pagto", ["dukamp_legacy_cpaautpg"]],
  ],
  [],
  [],
);

legacyProgram(
  "compras-setor",
  "MENU COMPRAS_SETOR",
  "cmpsetor.exe",
  [
    ["1", "Tabela Preco/Produto", ["dukamp_legacy_efaprodu"]],
    ["2", "Transferencia Produtos", ["dukamp_legacy_faaentit"]],
    ["3", "Pedidos Compra", ["dukamp_legacy_cmapedid", "dukamp_legacy_cmaitped"]],
  ],
  [
    ["1", "Produtos/Sugestao Compras", ["dukamp_legacy_efaprodu"]],
    ["2", "Curva ABC Fornec/Prod/Grupo", ["dukamp_legacy_efaprodu"]],
    ["3", "Agendamento Vendas", ["dukamp_legacy_faarepre"]],
    ["4", "Validade Produtos", ["dukamp_legacy_efavalid"]],
    ["5", "Margem de Venda", ["dukamp_legacy_efaprodu"]],
    ["6", "Tabela de Preco", ["dukamp_legacy_efaprodu"]],
  ],
  [
    ["1", "Notas Fiscal Venda", ["dukamp_legacy_faanotas"]],
    ["2", "Clientes/Titulos", ["dukamp_legacy_faaclien", "dukamp_legacy_cratitul"]],
    ["3", "Log Produtos", ["dukamp_legacy_efalogpr"]],
  ],
);

legacyProgram(
  "cadastros",
  "MENU CADASTROS",
  "fapmencd.exe",
  [
    ["1", "Clientes", ["dukamp_legacy_faaclien"]],
    ["2", "Fornecedores", ["dukamp_legacy_cpaforne"]],
    ["3", "Produtos", ["dukamp_legacy_efaprodu"]],
    ["4", "Vendedores", ["dukamp_legacy_faarepre"]],
    ["5", "Transportadoras", ["dukamp_legacy_faatrans"]],
  ],
  [
    ["1", "Clientes por Cidade", ["dukamp_legacy_faaclien"]],
    ["2", "Produtos por Grupo", ["dukamp_legacy_efaprodu"]],
  ],
  [
    ["1", "Clientes/Titulos", ["dukamp_legacy_faaclien"]],
    ["2", "Fornecedor/Titulos", ["dukamp_legacy_cpaforne"]],
    ["3", "Log Produtos", ["dukamp_legacy_efalogpr"]],
  ],
);
