// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SIGNUP_DEDUPE_WINDOW_MS = 5_000;

type CachedSignupRequest = {
  expiresAt: number;
  response: Promise<Response>;
};

const signupRequests = new Map<string, CachedSignupRequest>();

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function getRequestUrl(input: RequestInfo | URL): string {
  if (typeof input === 'string') return input;
  if (input instanceof URL) return input.toString();
  return input.url;
}

function getRequestMethod(input: RequestInfo | URL, init?: RequestInit): string {
  if (init?.method) return init.method.toUpperCase();
  if (typeof Request !== 'undefined' && input instanceof Request) return input.method.toUpperCase();
  return 'GET';
}

function getSignupRequestKey(input: RequestInfo | URL, init?: RequestInit): string {
  const body = typeof init?.body === 'string' ? init.body : '';
  return `${getRequestMethod(input, init)}:${getRequestUrl(input)}:${body}`;
}

function isSignupRequest(input: RequestInfo | URL, init?: RequestInit): boolean {
  return getRequestMethod(input, init) === 'POST' && getRequestUrl(input).includes('/auth/v1/signup');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    const requestInit = { ...init, headers };

    if (!isSignupRequest(input, init)) {
      return fetch(input, requestInit);
    }

    const key = getSignupRequestKey(input, init);
    const now = Date.now();
    const cached = signupRequests.get(key);

    if (cached && cached.expiresAt > now) {
      return (await cached.response).clone();
    }

    if (cached) signupRequests.delete(key);

    const networkRequest = fetch(input, requestInit);
    const cacheEntry: CachedSignupRequest = {
      expiresAt: now + SIGNUP_DEDUPE_WINDOW_MS,
      response: networkRequest.then((response) => response.clone()),
    };

    signupRequests.set(key, cacheEntry);

    cacheEntry.response.catch(() => {
      if (signupRequests.get(key) === cacheEntry) signupRequests.delete(key);
    });

    setTimeout(() => {
      if (signupRequests.get(key) === cacheEntry) signupRequests.delete(key);
    }, SIGNUP_DEDUPE_WINDOW_MS);

    return networkRequest;
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof localStorage !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
